KEYWORDS = [
    "tibbiy texnika",
    "tibbiy uskunalar",
    "tibbiy jihozlar",
    "tibbiy buyumlar",
    "laboratoriya uskunalari",
    "diagnostika uskunalari",
    "shifoxona jihozlari",
    "sterilizatsiya uskunalari",
    "tez yordam avtomobili",
    "медицинское оборудование",
    "медицинская техника",
    "медицинские изделия",
    "медицинская аппаратура",
    "лабораторное оборудование",
    "диагностическое оборудование",
    "оснащение больниц",
    "медицинские расходные материалы",
    "стерилизационное оборудование",
    "автомобиль скорой помощи",
    "medical equipment",
    "medical devices",
    "laboratory equipment",
    "diagnostic equipment",
    "hospital equipment",
    "medical supplies",
    "medical consumables",
    "imaging equipment",
    "ambulance",
    "supply installation commissioning",
    "MRI",
    "CT scanner",
    "angiography",
    "ultrasound",
    "ventilator",
    "defibrillator",
    "biochemistry analyzer",
    "hematology analyzer",
    "PCR",
    "HPLC",
]
