KEYWORDS = [
    "tibbiy texnika",
    "tibbiy uskunalar",
    "tibbiy jihozlar",
    "tibbiy buyumlar",
    "laboratoriya uskunalari",
    "diagnostika uskunalari",
    "shifoxona jihozlari",
    "sterilizatsiya uskunalari",
    "tez yordam avtomobili",
    "медицинское оборудование",
    "медицинская техника",
    "медицинские изделия",
    "медицинская аппаратура",
    "лабораторное оборудование",
    "диагностическое оборудование",
    "оснащение больниц",
    "медицинские расходные материалы",
    "стерилизационное оборудование",
    "автомобиль скорой помощи",
    "medical equipment",
    "medical devices",
    "laboratory equipment",
    "diagnostic equipment",
    "hospital equipment",
    "medical supplies",
    "medical consumables",
    "imaging equipment",
    "ambulance",
    "supply installation commissioning",
    "MRI",
    "CT scanner",
    "angiography",
    "ultrasound",
    "ventilator",
    "defibrillator",
    "biochemistry analyzer",
    "hematology analyzer",
    "PCR",
    "HPLC",
]

KEYWORDS.extend(
    [
        # Diagnostic and imaging
        "magnit-rezonans tomografiya",
        "kompyuter tomografiyasi",
        "rentgen apparati",
        "mammograf",
        "angiograf",
        "c-arm",
        "flyuorograf",
        "densitometr",
        "uzi apparati",
        "doppler apparati",
        "магнитно-резонансный томограф",
        "компьютерный томограф",
        "рентген аппарат",
        "маммограф",
        "ангиограф",
        "флюорограф",
        "денситометр",
        "узи аппарат",
        "допплер",
        "mri scanner",
        "x-ray machine",
        "mammography unit",
        "angiography system",
        "fluoroscopy",
        "bone densitometer",
        "ultrasound machine",
        "doppler system",
        # ICU and surgery
        "sun'iy nafas apparati",
        "narkoz apparati",
        "elektrokardiograf",
        "eeg apparati",
        "emg apparati",
        "endoskop",
        "laparoskop tizimi",
        "operatsion stol",
        "jarrohlik chirog'i",
        "gemodializ apparati",
        "bemor monitori",
        "infuzion nasos",
        "shprits nasosi",
        "kislorod kontsentratori",
        "avtoklav",
        "sterilizator",
        "аппарат ивл",
        "наркозный аппарат",
        "электрокардиограф",
        "ээг аппарат",
        "эмг аппарат",
        "эндоскоп",
        "лапароскопическая стойка",
        "операционный стол",
        "хирургический светильник",
        "аппарат для гемодиализа",
        "монитор пациента",
        "инфузионный насос",
        "шприцевой насос",
        "кислородный концентратор",
        "anesthesia machine",
        "ecg machine",
        "eeg device",
        "emg device",
        "laparoscopy tower",
        "operating table",
        "surgical light",
        "dialysis machine",
        "patient monitor",
        "infusion pump",
        "syringe pump",
        "oxygen concentrator",
        # Laboratory
        "biokimyo analizatori",
        "gematologik analizator",
        "immunoferment analizatori",
        "pcr qurilmasi",
        "real-time pcr",
        "hplc tizimi",
        "gaz xromatografi",
        "sentrifuga",
        "mikroskop",
        "laboratoriya muzlatgichi",
        "termostat",
        "inkubator",
        "gaz analizatori",
        "spektrofotometr",
        "reagentlar to'plami",
        "tibbiy diagnostika to'plamlari",
        "биохимический анализатор",
        "гематологический анализатор",
        "ифа анализатор",
        "пцр аппарат",
        "пцр в реальном времени",
        "вэжх система",
        "газовый хроматограф",
        "центрифуга",
        "микроскоп",
        "лабораторный холодильник",
        "газоанализатор",
        "спектрофотометр",
        "набор реагентов",
        "диагностические наборы",
        "elisa analyzer",
        "pcr device",
        "gas chromatograph",
        "centrifuge",
        "lab freezer",
        "gas analyzer",
        "spectrophotometer",
        "reagent kit",
        "diagnostic test kit",
        # Consumables
        "tibbiy kateter",
        "shprits",
        "jarrohlik asboblari",
        "implant",
        "ortopedik plastinka",
        "steril xalat",
        "steril qo'lqop",
        "bir martalik tibbiy niqob",
        "shovlar",
        "медицинский катетер",
        "шприц",
        "хирургический инструмент",
        "имплант",
        "ортопедическая пластина",
        "стерильный халат",
        "стерильные перчатки",
        "одноразовая медицинская маска",
        "хирургический шовный материал",
        "medical catheter",
        "surgical instrument",
        "orthopedic plate",
        "sterile gown",
        "sterile gloves",
        "disposable medical mask",
        "surgical suture",
        # Transport and infrastructure
        "sanitar transport",
        "mobil klinika",
        "tibbiy gaz tizimi",
        "markazlashtirilgan kislorod ta'minoti",
        "steril zona",
        "laboratoriya xonasini jihozlash",
        "operatsion blokni jihozlash",
        "shifoxona qurilishi",
        "tibbiyot markazini rekonstruksiya qilish",
        "medtexnikani o'rnatish",
        "санитарный транспорт",
        "мобильная клиника",
        "система медицинских газов",
        "централизованное кислородоснабжение",
        "стерильная зона",
        "оснащение лаборатории",
        "оснащение операционного блока",
        "строительство больницы",
        "реконструкция медицинского центра",
        "монтаж и ввод в эксплуатацию медтехники",
        "medical gas system",
        "central oxygen supply",
        "sterile zone",
        "laboratory room fitout",
        "operating block equipping",
        "hospital construction",
        "medical center reconstruction",
        "installation and commissioning of medical equipment",
        # Process terms
        "yetkazib berish va o'rnatish",
        "kafolat xizmati",
        "texnik xizmat ko'rsatish",
        "ishlab chiqaruvchi vakolatnomasi",
        "tender ta'minoti",
        "поставка и монтаж",
        "гарантийное обслуживание",
        "техническое обслуживание",
        "авторизационное письмо производителя",
        "тендерное обеспечение",
        "supply and installation",
        "warranty service",
        "maintenance service",
        "manufacturer authorization letter",
        "bid security",
        "tender guarantee",
    ]
)

KEYWORDS = list(dict.fromkeys(KEYWORDS))
